deepspeed --master_port=28500 train_reward.py \
    --use_special_tokens True \
    --lora_enable True \
    --vision_lora False \
    --freeze_vision_tower False \
    --freeze_llm False \
    --tune_merger True \
    --fps 2 \
    --max_frame_pixels 200704 \
    --sample_type "uniform" \
    --lora_r 64 \
    --lora_alpha 128 \
    --lora_namespan_exclude "['lm_head', 'rm_head', 'embed_tokens']" \
    --bf16 True \
    --torch_dtype "bfloat16" \
    --num_lora_modules -1 \
    --model_name_or_path ./model/Qwen3-VL-8B-Instruct \
    --meta_data "./datasets/train/example.csv" \
    --meta_data_test "./datasets/train/example.csv" \
    --output_dir test_result \
    --eval_dim "GSB" \
    --output_dim 1 \
    --reward_token "special" \
    --loss_type "bt" \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --num_train_epochs 4 \
    --learning_rate 2e-6 \
    --merger_lr 2e-6 \
    --vision_lr 2e-6 \
    --special_token_lr 2e-6 \
    --report_to tensorboard \
    --warmup_ratio 0.05 \
    --lr_scheduler_type "constant_with_warmup" \
    --eval_strategy "steps" \
    --logging_epochs 0.1 \
    --eval_epochs 0.1 \
    --save_epochs 0.5 \
    --max_length 6144 \
    --gradient_checkpointing True \
    --deepspeed ds_config/zero0.json \
    --save_only_model True \
    --seperate_save_model True \
    --save_full_model False \
    --return_token_logit \
    --dataloader_num_workers 8 \
    --enable_drop True